#! /bin/sh

ws0=web
ws1=term
ws2=chat
ws3=code
ws4=music
ws5=util
ws6=apple
ws7=panda
ws8=work
ws9=reaper

sxhkd &

#bspc monitor -d $ws0 $ws1 $ws2 $ws3 $ws4 $ws5 $ws6 $ws7 $ws8 $ws9


MONITOR_LIST=()
MON_NUM=$(bspc query -M | wc -l)
HOSTNAME=`hostname`
POLYBAR_RIGHT_ENABLE=true
MONITOR_MAIN=
MONITOR_RIGHT=


export MONITOR_LIST
export MONITOR_NUM
export HOSTNAME
export POLYBAR_RIGHT_ENABLE
export MONITOR_{MAIN,RIGHT}

case $HOSTNAME in
    "T450s")
        MONITOR_LIST=($(xrandr --listmonitors | sed '1 d' | awk 'NF>1{print $NF}'))
        #TODO: maxium support two monitors for now
        if [ ${#MONITOR_LIST[@]} -gt 1 ]; then

            MONITOR_MAIN=${MONITOR_LIST[0]}
            MONITOR_RIGHT=${MONITOR_LIST[1]}

            # enable or disable polybar on the second monitor
            if [ "$POLYBAR_RIGHT_ENABLE" = true ]; then
                #bspc monitor $MONITOR_MAIN -d $ws1 $ws2
                #bspc monitor $MONITOR_RIGHT -d $ws3 $ws4 $ws5 $ws6 $ws7 $ws8 $ws9 $ws0
                bspc monitor $MONITOR_MAIN -d $ws0 $ws1 $ws2 $ws3 $ws4 $ws5 $ws6 $ws7 $ws8 $ws9
                bspc monitor $MONITOR_RIGHT -d $ws0 $ws1 $ws2 $ws3 $ws4 $ws5 $ws6 $ws7 $ws8 $ws9
            else
                bspc monitor $MONITOR_MAIN -d  $ws1 $ws2 $ws3 $ws4 $ws5 $ws6 $ws7 $ws8 $ws9 $ws0
                bspc monitor $MONITOR_RIGHT -d $ws1
            fi

            xrandr --output $MONITOR_RIGHT --right-of $MONITOR_MAIN


        else
            MONITOR_MAIN=${MONITOR_LIST[0]}
            MONITOR_RIGHT=
            bspc monitor ^1 -d $ws0 $ws1 $ws2 $ws3 $ws4 $ws5 $ws6 $ws7 $ws8 $ws9
        fi


        bspc config focused_border_color "#ac7311"
        bspc config normal_border_color  "#3F3E3B"
        bspc config top_padding          15
        ;;

    "zhaoxin")
        #notice: sudo apt-get install jq
        mon=$(bspc query -M)
        for i in $mon; do
            MONITOR_LIST=("${MONITOR_LIST[@]}" $(bspc query -T -m $i | jq -r .name))
        done

        if [ ${#MONITOR_LIST[@]} -gt 1 ]; then
            MONITOR_MAIN=${MONITOR_LIST[0]}
            MONITOR_RIGHT=${MONITOR_LIST[1]}
            xrandr --output $MONITOR_RIGHT --right-of $MONITOR_MAIN

            bspc monitor $MONITOR_MAIN -d $ws0 $ws1 $ws2 $ws3 $ws4 $ws5 $ws6 $ws7 $ws8 $ws9
            bspc monitor $MONITOR_RIGHT -d $ws0 $ws1 $ws2 $ws3 $ws4 $ws5 $ws6 $ws7 $ws8 $ws9
        else
            MONITOR_MAIN=${MONITOR_LIST[0]}
            MONITOR_RIGHT=
            bspc monitor ^1 -d $ws0 $ws1 $ws2 $ws3 $ws4 $ws5 $ws6 $ws7 $ws8 $ws9
        fi


        bspc config focused_border_color "#77dd77"
        bspc config normal_border_color  "#3F3E3B"
        bspc config top_padding          20
        ;;
esac

#When focusing a monitor, put the pointer at its center
bspc config focus_follows_monitor true
bspc config pointer_modifier  mod1

bspc config ignore_ewmh_focus   true
bspc config initial_polarity    second_child
bspc config presel_feedback_color        "#26262b"

bspc config border_width        3
bspc config window_gap          8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config history_aware_focus  true
bspc config focus_follows_pointer true

bspc rule -a Gimp  state=floating
bspc rule -a Google-chrome state=floating
bspc rule -a Firefox  state=floating
bspc rule -a remmina state=floating

#use 'xprop | awk '/WM_CLASS/{print $4}' to print the prog name you clicks
#use bspc rule -l to list the rules
#use bspc rule -r to remove the rule, eg: bspc rule -r Bcompare
bspc rule -a P4v.bin  state=floating
bspc rule -a Bcompare state=floating
bspc rule -a Sublime_text state=fullscreen

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

if [ -f "$HOME/.startup.sh" ]; then
    . "$HOME/.startup.sh"
fi
